parameters:
#    calitarus_bit_pay.example.class: Calitarus\BitPayBundle\Example

services:
#    calitarus_bit_pay.example:
#        class: %calitarus_bit_pay.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
